print(('True and True ')+(str(True and True)))
print(('True and False ')+(str(True and False)))
print(('False and True ')+(str(True and False)))
print(('False and False ')+(str(False and False)))
# print("True and True")
# print(True and True)
# print(True and True), print('True and True')
